@startuml
left to right direction

actor "User" as U
actor "Technician" as T
actor "Tension_Sensor" as TS
actor "Elevator_Sensor" as ES

package Elevator {
	usecase "Request Floor" as UC1
	usecase "Request Elevator" as UC2
	usecase "Initiate Catch Clamp" as UC3
	usecase "Update Floor indicator" as UC4
}
U --> UC1
U --> UC2
T --> UC1
T --> UC2
T --> UC3
TS --> UC3
T --> UC4
ES --> UC4
@enduml