@startuml
'skinparam linetype ortho

' events!!
' state exit and enter actions
' programs selection
' update screen
' check oven temp
' switch kneading direction
' ingredient addition

' look at the microwave project

[*] --> standby
standby --> awake : start button pressed
awake --> standby : long-press menu button

note right
state can change from any awake sub-state
to standby when a long-press on the menu
button is detected
end note

state awake {
	[*] --> no_indicator
	no_indicator ---> standby : no buttons have been pressed for 5 minutes
	no_indicator --> waiting : when the selected program is started
	no_indicator --> baking : if bake only is started
	waiting --> kneading
	kneading --> rising
	rising --> baking
	rising --> done : if the dough only program was started
	baking --> done
}

@enduml