---
title: "Template R notebook met SQL code"
output:
  html_document: default
  pdf_document: default
---


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Instructies:                                                                                            +
+ Onderstaande is nodig om je notebook werkende te krijgen.                                               +
+ Bij het opstarten van je notebook dien je de chunk van regel 28 t/m 40 en regel 42 t/m 46 te runnen.    +
+ Daarna spring je naar regel 76 waar je je eerste SQL-chunk kan maken.                                   +
+                                                                                                         +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


Dit is een voorbeeld van hoe je aan de slag zou kunnen gaan met R chunks in een Notebook.
Hierin ga je:
+ opmaak toepassen
+ functies uit Datacamp toepassen op een "eigen" dataset
+ oefenen met "knitten"
Er is met zogenaamde Markdown allerlei opmaak toegepast op de tekst rondom de chunks. Dit is anders dan hoe het in Word gaat (daar is het meer What You See Is What You Get), het is wel vergelijkbaar met de opmaak van pagina's in Wikipedia.

## Importeren libraries en dataset
Hieronder wordt een library geladen waar functies in zitten die we verderop in het Notebook gaan gebruiken: tidyverse. Daarnaast wordt hier de dataset geïmporteerd zodat we daar vragen aan kunnen stellen. 


## Setup
```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(readxl)

dataset <- read_excel("VerkoopSupermarktProducten.xlsx")

con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, dataset, overwrite = TRUE)

knitr::opts_chunk$set(connection = "con")

```

```{sql connection=con}
UPDATE dataset SET besteldatum = DATE(besteldatum, 'unixepoch'), leverdatum = DATE(leverdatum, 'unixepoch'), betaaldatum = DATE(betaaldatum, 'unixepoch');
```


Als je bovenstaande code uitvoert door op het groene pijltje rechtsbovenin de chunk te drukken, gebeurt er nog vrij weinig. Als het goed is verschijnt er alleen even een groen balkje naast de code regels. Tenminste, als je het Excel bestand op de juiste plek hebt geüpload.
Het laden van de libraries hoeven we maar 1 keer te doen en het is wel zo overzichtelijk om dat allemaal aan het begin van je document te doen voor je de inhoud in duikt.

De dataset is nu opgeslagen in een database waarvoor we een connectie hebben gemaakt die 'con' heet. Elke keer als we dus gegevens uit die database willen halen zullen we dus eerst die connectie moeten gaan noemen.


## eerste SQL-chunk
In de onderstaande chunk is de meest basale vorm van een query opgesteld. Je kan deze laten uitvoeren door op de groene knop te drukken of door de query-code te selecteren en op *Ctrl+Shift+Enter* te drukken.
Merk ook de eerste regel op waarin 'connection=con' staat. Deze is nodig om contact met de database te maken.

```{sql connection=con}
select *
from dataset
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Opdracht                                                                                                            +
+ Bouw een aantal SQL-queries die interessante informatie opvragen uit de data. Je kan denken aan vragen zoals        +
+  - Hoeveel verschillende verkopers zijn er?                                                                         +
+  - Hoeveel verkopers per regio zijn er?                                                                             +
+                                                                                                                     +
+ Maak zo meer SQL-queries op de gegeven dataset (of een eigen dataset) waarin gebruik gemaakt is van onder andere    +
+ WHERE, ORDER BY, GROUP BY, HAVING en subqueries;                                                                    +
+                                                                                                                     +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```{sql connection=con}
/*
vraag: wat is de meest waardevolle regio

uit: omzet, aantal producten en omzet per product van elke regio

waarom: om te zien of bepaalde prijzen het goed doen in bepaalde regio's. Zo kan je bijvoorbeeld de prijzen voor bepaalde regio's verlagen of juist verhogen.

conclusie: omzet word het meest beinvloed door het aantal verkochte producten dus om de omzet te verhogen moeten de producten in de regio's RHMD en GVGH aantrekkelijker worden hiervoor moet gekeken worden naar de product prijzen in de verschillende regios
*/
select regiocode, sum(regelomzet) as omzet, sum(aantal) as aantal_producten, (sum(regelomzet) / sum(aantal)) as gemiddelde_omzet_per_product
from dataset
group by regiocode
order by omzet desc;
```

```{sql connection=con}
/*
vraag: welke producten genereren de meeste omzet tegen het aantal verkocht in de verschillende regio's

uit: omzet per product tegen aantal verkocht in de verschillende regio's

waarom: om te kijken of prijs aanpassingen nodig zijn in de verschillende regio's

conclusie: de ganzen lever in de regio REHV is minder aantrekkelijk dan in de regio RHMD hier zou het handig kunnen zijn om de prijs aan te passen
*/
select regiocode, omschrijving, sum(aantal) as aantal_verkocht, sum(regelomzet) as omzet, (sum(regelomzet) / sum(aantal)) as gemiddelde_omzet
from dataset
group by regiocode, omschrijving
order by omschrijving asc, omzet desc;
```



```{sql connection=con}
/*
vraag: wat is de meest waardevolle klant

uit: gemmidelde omzet per klant

waarom: om korting te geven of een reclame stunt te doen

conclusie: Bakermans (20) is heeft de hoogste gemiddelde omzet
*/
select klantnr, naam, avg(regelomzet) as gemiddelde_omzet
from dataset
group by klantnr
order by naam;
```
```{sql connection=con}
/*
vraag: in welke maand word de gemiddeld meeste omzet gegenereerd

uit: gemiddeldelde omzet per maand

waarom: om te voorspellen of er volgende maand budget vrij komt voor uitbreiding

conclusie: in de volgende maand (11) werd vorig jaar ongeveer 10500 euro omzet gedraaid dit is (bijvoobeeld) minder dan deze maand dus er zal waarschijnlijk geen budget vrijkomen
*/
select strftime('%m', besteldatum, 'unixepoch') as maand, round(sum(regelomzet)) as omzet
from dataset
group by maand
order by maand;
```




```{sql connection=con}
/*
vraag: welke bestellingen duren het langst

uit: bestel tijd per klant

waarom: met deze informatie kan je de bestellingen voor bepaalde klanten prioritiseren zodat elke klant ongeveer dezelfde besteltijd heeft

conclusie: Van der heiden moet gemiddeld het langste wachten op zijn/haar bestelling dus het kan verstandig zijn om prioriteit te geven aan die bestellingen
*/
select klantnr, naam, avg(cast(strftime('%d', leverdatum - besteldatum, 'unixepoch') as integer)) as gemiddelde_bezorgtijd
from dataset
group by klantnr
order by gemiddelde_bezorgtijd desc;
```
```{sql connection=con}
/*
vraag: welke bestellingen duren het langst in Eindhoven

uit: bestel tijd per klant uit Eindhoven

waarom: met deze informatie kan je de bestellingen voor bepaalde klanten prioritiseren zodat elke klant ongeveer dezelfde besteltijd heeft

conclusie: Jansen moet gemiddeld het langste wachten op zijn/haar bestelling dus het kan verstandig zijn om prioriteit te geven aan die bestellingen
*/
select klantnr, naam, avg(cast(strftime('%d', leverdatum - besteldatum, 'unixepoch') as integer)) as gemiddelde_bezorgtijd
from dataset
group by klantnr
having woonplaats = 'Eindhoven'
order by gemiddelde_bezorgtijd desc;
```


Nieuwe query's kan je aanroepen door in de balk van dit subscherm op het pijltje naast het groene C-knopje te drukken en te kiezen voor SQL. Vergeet niet de connectie 'con' heet en daar aan moet linken, net zoals de bovenstaande query's.



De resultaten van het notebook kan je opslaan als een HTML-pagina. Om dat te doen klik je in de bovenstaande balk op de pijl naast *Preview* en selecteer je *Knit to HTML*. Een andere optie is om *Ctrl+Shift+K* in te drukken om een HTML bestand te krijgen.
