@startuml
autonumber

participant Elevator_Sensor as ES
participant Floor as F
participant Elevator as E
participant Floor_Indicator_floor as FIf
participant Floor_Indicator_elevator as FIe

ES		->		F:		handle_elevator
F		->		FIf:	update
FIf		-->		F:		ok
F		->		E:		set_floor
E		->		FIe:	update
FIe		-->		E:		ok
E		-->		F:		ok




@enduml